
spring.application.name=Proyecto_Avanzada
#Manuel Pineda Varela
#Carlos Alonso Barahona
#Santiago Solarte Trujillo

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# If you want to use Postgres locally, set these environment variables before running:
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/proyecto_avanzada
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=admin

# Server port (changed to 8082 to avoid conflicts on 8080)
server.port=8082
# correr con .\gradlew.bat bootRun 