
# ==========================================
# Base de Datos
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/proyecto_avanzada
spring.datasource.username=postgres
spring.datasource.password=admin

# ==========================================
# Servidor
# ==========================================

server.port=8082
spring.application.name=Proyecto_Avanzada
